'use strict'
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

let materialChk = new Schema({
    indu_id:{type: mongoose.Schema.ObjectId, ref:'Industry_master'},
    product_id:{type: mongoose.Schema.ObjectId, ref:'Material_master'},
    material0:{type: mongoose.Schema.ObjectId, ref:'Material_master'},
    material0_qty:{type: String, trim: true},
    material1:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material1_qty:{type: String, trim: true},
    material2:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material2_qty:{type: String, trim: true},
    material3:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material3_qty:{type: String, trim: true},
    material4:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material4_qty:{type: String, trim: true},
    material5:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material5_qty:{type: String, trim: true},
    material6:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material6_qty:{type: String, trim: true},
    material7:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material7_qty:{type: String, trim: true},
    material8:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material8_qty:{type: String, trim: true},
    material9:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material9_qty:{type: String, trim: true},
    material10:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material10_qty:{type: String, trim: true},
    material11:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material11_qty:{type: String, trim: true},
    material12:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material12_qty:{type: String, trim: true},
    material13:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material13_qty:{type: String, trim: true},
    material14:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material14_qty:{type: String, trim: true},
    material15:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material15_qty:{type: String, trim: true},
    material16:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material16_qty:{type: String, trim: true},
    material17:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material17_qty:{type: String, trim: true},
    material18:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material18_qty:{type: String, trim: true},
    material19:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material19_qty:{type: String, trim: true},
    material20:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material20_qty:{type: String, trim: true},
    material21:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material21_qty:{type: String, trim: true},
    material22:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material22_qty:{type: String, trim: true},
    material23:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material23_qty:{type: String, trim: true},
    material24:{type : mongoose.Schema.ObjectId, ref:'Material_master'},
    material24_qty:{type: String, trim: true},
},{
    timestamps: true,
    versionKey: false
});

module.exports=mongoose.model('MaterialChk', materialChk, 'materialChk');